name: Build and Deploy to Development

on:
  push:
    branches:
      - feat/*

permissions:
  id-token: write
  contents: read
  actions: read

env:
  PROJECT_ID: admin-vue-op

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create Root .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_API_BASE_URL: https://develop-api.afungame9.com
          directory: ./
          file_name: .env
          fail_on_empty: false

      - name: Build
        run: |
          yarn install --network-concurrency=1
          yarn vite build --config ./config/vite.config.dev.ts

      - name: Sync static assets
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --exclude 'index.html'
        env:
          AWS_S3_BUCKET: ${{ secrets.DEVELOP_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEVELOP_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEVELOP_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'sa-east-1' # optional: defaults to us-east-1
          SOURCE_DIR: 'dist' # optional: defaults to entire repository

      - name: Sync index.html
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --exclude 'assets/*' --cache-control 'no-cache'
        env:
          AWS_S3_BUCKET: ${{ secrets.DEVELOP_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEVELOP_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEVELOP_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'sa-east-1' # optional: defaults to us-east-1
          SOURCE_DIR: 'dist' # optional: defaults to entire repository

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: message,commit,action,eventName,ref,workflow,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
